/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import processos.Data;
import entidades.Usuario;

/**
 *
 * @author atom
 */
public class Menu extends javax.swing.JFrame {
    
    Usuario user;

    /**
     * Creates new form Inicio
     */
    public Menu() {
        initComponents();
        this.user = new Usuario();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPolicia = new java.awt.Button();
        jButtonChamarContatoEmergencia = new java.awt.Button();
        jButtonSAMU = new java.awt.Button();
        jButtonBombeiros = new java.awt.Button();
        jMenuBarConfiguracoes = new javax.swing.JMenuBar();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenuItemEditarPerfil = new javax.swing.JMenuItem();
        jMenuItemContatosDeEmergencia = new javax.swing.JMenuItem();
        jMenuItemMensagensPreProgramadas = new javax.swing.JMenuItem();
        jMenuItemSuporte = new javax.swing.JMenuItem();
        jMenuItemDesconectar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jButtonPolicia.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButtonPolicia.setLabel("Polícia");

        jButtonChamarContatoEmergencia.setLabel("Contatos de Emergência");

        jButtonSAMU.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButtonSAMU.setLabel("SAMU");

        jButtonBombeiros.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButtonBombeiros.setLabel("Bombeiros");

        jMenuConfiguracoes.setText("Configurações");

        jMenuItemEditarPerfil.setText("Editar Perfil");
        jMenuItemEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarPerfilActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemEditarPerfil);

        jMenuItemContatosDeEmergencia.setText("Contatos de Emergência");
        jMenuItemContatosDeEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContatosDeEmergenciaActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemContatosDeEmergencia);

        jMenuItemMensagensPreProgramadas.setText("Mensagens Pré-Programadas");
        jMenuConfiguracoes.add(jMenuItemMensagensPreProgramadas);

        jMenuItemSuporte.setText("Suporte");
        jMenuConfiguracoes.add(jMenuItemSuporte);

        jMenuItemDesconectar.setText("Desconectar");
        jMenuItemDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesconectarActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemDesconectar);

        jMenuBarConfiguracoes.add(jMenuConfiguracoes);

        setJMenuBar(jMenuBarConfiguracoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBombeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChamarContatoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSAMU, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPolicia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonPolicia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonBombeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButtonSAMU, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButtonChamarContatoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarPerfilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Perfil perf = new Perfil();
        perf.iniciar(this.user);
    }//GEN-LAST:event_jMenuItemEditarPerfilActionPerformed

    private void jMenuItemContatosDeEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContatosDeEmergenciaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ContatosEmergencia ce = new ContatosEmergencia();
        ce.iniciar(this.user);        
    }//GEN-LAST:event_jMenuItemContatosDeEmergenciaActionPerformed

    private void jMenuItemDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesconectarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String a[] = {};
        Login.main(a);
    }//GEN-LAST:event_jMenuItemDesconectarActionPerformed

    public void iniciar(Usuario user) throws IOException{
        this.user = Data.buscar_usuario(user.getCpf());
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jButtonBombeiros;
    private java.awt.Button jButtonChamarContatoEmergencia;
    private java.awt.Button jButtonPolicia;
    private java.awt.Button jButtonSAMU;
    private javax.swing.JMenuBar jMenuBarConfiguracoes;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuItemContatosDeEmergencia;
    private javax.swing.JMenuItem jMenuItemDesconectar;
    private javax.swing.JMenuItem jMenuItemEditarPerfil;
    private javax.swing.JMenuItem jMenuItemMensagensPreProgramadas;
    private javax.swing.JMenuItem jMenuItemSuporte;
    // End of variables declaration//GEN-END:variables
}
